# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Git guide
tagline:          'The starter guide for your student project'
description:      'A Git starter guide for students at Malmö högskola'
url:              http://hyde.getpoole.com
baseurl:          /da336a/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
